name: QuantConnect Data Scraper

on:
  # Run this workflow automatically every day at 1:00 AM UTC.
  schedule:
    - cron: '0 1 * * *'
  # Also allow running it manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Set up Google Chrome (for Selenium)
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas

      # Step 5: Run the scraper script
      - name: Run QuantConnect Scraper
        env:
          # Use the secrets you configured in your GitHub repo settings
          QC_USERNAME: ${{ secrets.QC_USERNAME }}
          QC_PASSWORD: ${{ secrets.QC_PASSWORD }}
        run: python data_scraper.py

      # Step 6: Commit the new data file back to your repository
      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update financial data" && git push
